x1 = str("Hello World")
x2 = int(5)
x3 = float(5.50)
x4 = complex(1j)
x5 = list(("apple", "banana", "mango"))
x6 = tuple(("apple", "banana", "mango"))
x7 = range(6)
x8 = dict(name="akash", age="21")
x9 = set(("apple", "banana", "mango"))
x10 = bool(5)
x11 = bytes(5)
x12 = bytearray(5)
x13 = frozenset(("apple", "banana", "mango"))
x14 = memoryview(bytes(5))
#printing all varables
print(x1)
print(x2)
print(x3)
print(x4)
print(x5)
print(x6)
print(x7)
print(x8)
print(x9)
print(x10)
print(x11)
print(x12)
print(x13)
print(x14)
#printing all datatypes by using type func
print(type(x1)) 
print(type(x2))
print(type(x3))
print(type(x4))
print(type(x5))
print(type(x6))
print(type(x7))
print(type(x8))
print(type(x9))
print(type(x10))
print(type(x11))
print(type(x12))
print(type(x13))
print(type(x14))